const item = (name, serving, calories, protein, carbs, fat, options = {}) => ({
  name,
  serving,
  calories,
  protein,
  carbs,
  fat,
  ...options,
});

window.RESTAURANT_DATA = {
  chipotle: {
    id: "chipotle",
    name: "Chipotle",
    kicker: "Build a burrito, bowl, salad, or tacos",
    description:
      "Stack tortillas, rice, beans, proteins, salsas, and extras the same way you order in line.",
    note:
      "A bowl starts at zero macros, so only add the tortilla or salad greens if you want them counted.",
    source: {
      label: "US Nutrition Facts Paper Menu",
      updated: "Official PDF posted on Chipotle's site",
      url: "https://www.chipotle.com/content/dam/chipotle/menu/nutrition/US-Nutrition-Facts-Paper-Menu-3-2025.pdf",
    },
    tips: [
      "Use 3 taco tortillas for a standard taco order.",
      "Tap plus again for double rice, double beans, or extra protein.",
    ],
    theme: {
      brand: "#a7501e",
      accent: "#f0bb66",
      wash: "#fff2e7",
      glow: "rgba(240, 187, 102, 0.38)",
    },
    categories: [
      {
        id: "build-base",
        title: "Build base",
        description: "Choose the shell or greens that define the meal style.",
        items: [
          item("Flour Tortilla (burrito)", "1 tortilla", 320, 8, 50, 9),
          item("Flour Tortilla (taco)", "1 tortilla", 80, 2, 13, 2.5, {
            note: "Add 3 for a full soft taco order.",
          }),
          item("Crispy Corn Tortilla", "1 tortilla", 70, 1, 10, 3, {
            note: "Add 3 for a full crispy taco order.",
          }),
          item("Supergreens Salad Mix", "3 oz", 15, 1, 3, 0),
        ],
      },
      {
        id: "rice-beans",
        title: "Rice, beans, and veggies",
        description: "Load up the bowl with the usual foundation pieces.",
        items: [
          item("Cilantro-Lime Brown Rice", "4 oz", 210, 4, 36, 6),
          item("Cilantro-Lime White Rice", "4 oz", 210, 4, 40, 4),
          item("Black Beans", "4 oz", 130, 8, 22, 1.5),
          item("Pinto Beans", "4 oz", 130, 8, 21, 1.5),
          item("Fajita Vegetables", "2 oz", 20, 1, 5, 0),
        ],
      },
      {
        id: "proteins",
        title: "Proteins",
        description: "Single or double up your main protein.",
        items: [
          item("Chicken", "4 oz", 180, 32, 0, 7),
          item("Steak", "4 oz", 150, 21, 1, 6),
          item("Barbacoa", "4 oz", 170, 24, 2, 7),
          item("Carnitas", "4 oz", 210, 23, 0, 12),
          item("Sofritas", "4 oz", 150, 8, 9, 10),
        ],
      },
      {
        id: "toppings",
        title: "Salsas and toppings",
        description: "All the flavor add-ons that make the meal yours.",
        items: [
          item("Fresh Tomato Salsa", "4 oz", 25, 0, 4, 0),
          item("Roasted Chili-Corn Salsa", "4 oz", 80, 3, 16, 1.5),
          item("Tomatillo-Green Chili Salsa", "2 fl oz", 15, 0, 4, 0),
          item("Tomatillo-Red Chili Salsa", "2 fl oz", 30, 0, 4, 0),
          item("Cheese", "1 oz", 110, 6, 1, 8),
          item("Sour Cream", "2 oz", 110, 2, 2, 9),
          item("Romaine Lettuce", "1 oz", 5, 0, 1, 0),
        ],
      },
      {
        id: "extras",
        title: "Extras and sides",
        description: "Count the premium extras or side add-ons too.",
        items: [
          item("Guacamole", "4 oz", 230, 2, 8, 22),
          item("Queso Blanco", "2 oz", 120, 5, 4, 9),
          item("Chipotle-Honey Vinaigrette", "2 fl oz", 220, 1, 18, 16),
          item("Chips", "4 oz", 540, 7, 73, 25),
        ],
      },
    ],
  },
  cava: {
    id: "cava",
    name: "CAVA",
    kicker: "Mediterranean bowls, pitas, and plates",
    description:
      "Mix grains, greens, mains, toppings, spreads, dressings, and pita with build-your-own flexibility.",
    note:
      "Values are per official serving, so stacking dips, dressings, or pita can move the totals quickly.",
    source: {
      label: "CAVA Nutritional and Allergen Guide",
      updated: "Official PDF from January 2026",
      url: "https://assets.ctfassets.net/kugm9fp9ib18/7KrOGNUFZjBddOWezWLWwm/7ee5521df4ce80d5a2021523bff12803/CAVA-REC-GID-0126-AllergNutritnReg.pdf",
    },
    tips: [
      "CAVA builders often use multiple bases, so mix greens and grains freely.",
      "Dressings like Garlic Dressing and Greek Vinaigrette swing fat totals fast.",
    ],
    theme: {
      brand: "#2f6a47",
      accent: "#d7b45c",
      wash: "#eef8f0",
      glow: "rgba(120, 191, 138, 0.32)",
    },
    categories: [
      {
        id: "greens-grains",
        title: "Greens and grains",
        description: "Start with one base or combine a few.",
        items: [
          item("Brown Rice", "1 serving", 310, 7, 48, 10),
          item("Saffron Basmati Rice", "1 serving", 290, 5, 54, 7),
          item("Black Lentils", "1 serving", 270, 18, 37, 7),
          item("SuperGreens", "1 serving", 35, 3, 6, 0.5),
          item("Arugula", "1 serving", 20, 2, 3, 0.5),
          item("Baby Spinach", "1 serving", 20, 3, 3, 0),
          item("Romaine", "1 serving", 20, 1, 4, 0),
          item("Power Greens", "1 serving", 30, 2, 4, 0),
        ],
      },
      {
        id: "mains",
        title: "Mains",
        description: "Pick the protein or veggie anchor for the meal.",
        items: [
          item("Braised Lamb", "1 serving", 210, 24, 2, 12),
          item("Grilled Chicken", "1 serving", 250, 28, 3, 13),
          item("Falafel", "1 serving", 350, 6, 24, 26),
          item("Grilled Steak", "1 serving", 170, 23, 1, 9),
          item("Harissa Honey Chicken", "1 serving", 260, 26, 7, 14),
          item("Roasted Vegetables", "1 serving", 100, 3, 14, 4.5),
          item("Spicy Lamb Meatballs", "1 serving", 300, 24, 3, 21),
          item("White Sweet Potatoes", "1 serving", 180, 3, 35, 4),
        ],
      },
      {
        id: "toppings",
        title: "Toppings",
        description: "Crunch, brine, and fresh toppings all count here.",
        items: [
          item("Shredded Romaine", "1 serving", 5, 0, 1, 0),
          item("Pita Crisps", "1 serving", 70, 1, 6, 11),
          item("Sumac Slaw", "1 serving", 30, 1, 3, 1.5),
          item("Tomato + Onion", "1 serving", 20, 0, 2, 1.5),
          item("Persian Cucumber", "1 serving", 15, 0, 1, 1),
          item("Tomato + Cucumber", "1 serving", 5, 0, 1, 0),
          item("Kalamata Olives", "1 serving", 35, 0, 2, 3),
          item("Fiery Broccoli", "1 serving", 35, 1, 2, 2.5),
          item("Pickled Onions", "1 serving", 20, 0, 5, 0),
          item("Salt-Brined Pickles", "1 serving", 5, 0, 0, 0),
          item("Crumbled Feta", "1 serving", 35, 3, 0, 2.5),
          item("Fire-Roasted Corn", "1 serving", 45, 1, 5, 2.5),
          item("Avocado", "1 serving", 110, 1, 6, 10),
        ],
      },
      {
        id: "spreads",
        title: "Dips and spreads",
        description: "Layer on the creamy or spicy extras.",
        items: [
          item("Tzatziki", "1 serving", 30, 2, 1, 2.5),
          item("Hummus", "1 serving", 50, 2, 4, 2.5),
          item("Roasted Eggplant", "1 serving", 50, 0, 2, 5),
          item("Crazy Feta", "1 serving", 70, 4, 1, 6),
          item("Harissa", "1 serving", 70, 1, 5, 6),
          item("Red Pepper Hummus", "1 serving", 40, 2, 5, 1.5),
        ],
      },
      {
        id: "dressings",
        title: "Dressings",
        description: "Use one or compare a few dressing combos.",
        items: [
          item("Balsamic Date Vinaigrette", "1 serving", 60, 0, 7, 4),
          item("Yogurt Dill", "1 serving", 30, 2, 1, 2),
          item("Lemon Herb Tahini", "1 serving", 70, 2, 4, 6),
          item("Tahini Caesar", "1 serving", 90, 2, 3, 8),
          item("Greek Vinaigrette", "1 serving", 130, 0, 1, 14),
          item("Skhug", "1 serving", 80, 0, 1, 9),
          item("Hot Harissa Vinaigrette", "1 serving", 70, 0, 1, 7),
          item("Garlic Dressing", "1 serving", 180, 0, 0, 20),
        ],
      },
      {
        id: "sides",
        title: "Pita and sides",
        description: "Count the bread, chips, or a little extra crunch.",
        items: [
          item("Whole Pita", "1 pita", 320, 13, 54, 6),
          item("Side Pita", "1 side pita", 80, 3, 14, 1.5),
          item("Pita Chips", "1 serving", 280, 10, 41, 8),
          item("Sumac Sour Cream + Onion Pita Chips", "1 serving", 290, 10, 43, 9),
        ],
      },
    ],
  },
  sweetgreen: {
    id: "sweetgreen",
    name: "Sweetgreen",
    kicker: "Custom salads, bowls, and warm add-ons",
    description:
      "Build from bases, crunchy toppings, premiums, proteins, and dressings using Sweetgreen's ingredient nutrition overview.",
    note:
      "Sweetgreen's official PDF notes that ingredient availability can vary by market and some items are seasonal.",
    source: {
      label: "Sweetgreen Nutrition Overview + Ingredients",
      updated: "Official PDF last updated July 2024",
      url: "https://assets.ctfassets.net/eum7w7yri3zr/3QCThKO0fcZzRZe1AcKKbj/613337e7065c17e4c07b245d4713a2cc/Nutrition_Overview_P7_24.pdf",
    },
    tips: [
      "Premium proteins and dressings can add up fast, especially with avocado or steak.",
      "You can blend salad greens and grains the same way Sweetgreen mixes bases in-store.",
    ],
    theme: {
      brand: "#365d2b",
      accent: "#a6cf68",
      wash: "#f1f7e8",
      glow: "rgba(166, 207, 104, 0.34)",
    },
    categories: [
      {
        id: "bases",
        title: "Bases",
        description: "Start with greens, grains, or both.",
        items: [
          item("Arugula", "60 g", 15, 2, 2, 0),
          item("Baby Spinach", "53 g", 15, 1, 2, 0),
          item("Chopped Romaine", "140 g", 25, 1, 3, 0),
          item("Herbed Quinoa", "100 g", 130, 5, 21, 3),
          item("Shredded Kale", "70 g", 35, 3, 6, 1),
          item("Spring Mix", "70 g", 15, 0, 0, 0),
          item("White Rice", "95 g", 120, 2, 27, 1),
          item("Wild Rice", "95 g", 155, 3, 31, 2),
          item("Bread", "34 g", 80, 3, 18, 0),
        ],
      },
      {
        id: "toppings",
        title: "Toppings",
        description: "Crunch, herbs, fruit, and fresh veggie layers.",
        items: [
          item("Apples", "32 g", 20, 0, 4, 0),
          item("Basil", "7 g", 0, 0, 0, 0),
          item("Chickpeas", "43 g", 45, 2, 7, 0.5),
          item("Cilantro", "5 g", 0, 0, 0, 0),
          item("Crispy Onions", "6 g", 40, 0, 3, 3),
          item("Crispy Rice", "26 g", 80, 2, 14, 2),
          item("Cucumbers", "44 g", 5, 0, 1, 0),
          item("Nori Sesame Seasoning", "2 g", 5, 1, 0, 0),
          item("Pickled Onions", "38 g", 20, 0, 5, 0),
          item("Raw Carrots", "23 g", 10, 0, 2, 0),
          item("Roasted Almonds", "14 g", 80, 3, 3, 6),
          item("Roasted Sweet Potatoes", "39 g", 65, 1, 13, 1),
          item("Shredded Cabbage", "25 g", 10, 0, 2, 0),
          item("Spicy Broccoli", "33 g", 25, 1, 3, 1),
          item("Tomatoes", "46 g", 10, 1, 2, 0),
          item("Tortilla Chips", "16 g", 80, 1, 10, 4),
          item("Zaatar Breadcrumbs", "15 g", 65, 3, 9, 2),
        ],
      },
      {
        id: "premiums",
        title: "Premiums and proteins",
        description: "Cheese, eggs, avocado, and higher-impact proteins all live here.",
        items: [
          item("Blue Cheese", "30 g", 110, 6, 1, 9),
          item("Goat Cheese", "34 g", 90, 7, 0, 7),
          item("Hard Boiled Egg", "50 g", 70, 7, 1, 5),
          item("Hummus", "47 g", 80, 4, 7, 5),
          item("Parmesan Crisps", "20 g", 100, 6, 1, 8),
          item("Shaved Parmesan", "17 g", 65, 6, 0, 4),
          item("Veg Slaw", "46 g", 60, 1, 4, 5),
          item("Avocado", "87 g", 160, 3, 8, 13),
          item("Blackened Chicken", "80 g", 110, 15, 1, 5),
          item("Caramelized Garlic Steak", "100 g", 320, 21, 7, 24),
          item("Miso Glazed Salmon", "132 g", 290, 24, 13, 15),
          item("Roasted Chicken", "78 g", 110, 21, 1, 2),
          item("Roasted Tofu", "75 g", 100, 7, 2, 7),
          item("Warm Portobello Mix", "65 g", 110, 5, 6, 8),
          item("Warm Roasted Sweet Potatoes", "72 g", 85, 2, 15, 2),
        ],
      },
      {
        id: "dressings",
        title: "Dressings and finishing touches",
        description: "These can be light, punchy, or surprisingly macro-heavy.",
        items: [
          item("Balsamic Vinaigrette", "41 g", 210, 0, 5, 22),
          item("Balsamic Vinegar", "15 g", 15, 0, 3, 0),
          item("Caesar", "39 g", 160, 1, 1, 17),
          item("Extra Virgin Olive Oil", "15 g", 130, 0, 0, 14),
          item("Green Goddess Ranch", "35 g", 170, 1, 1, 18),
          item("Honey BBQ Sauce", "30 g", 40, 0, 4, 0),
          item("Hot Honey Mustard Sauce", "41 g", 170, 0, 9, 14),
          item("Lemon Squeeze", "15 g", 0, 0, 1, 0),
          item("Lime Cilantro Jalapeno Vinaigrette", "37 g", 140, 0, 4, 14),
          item("Lime Squeeze", "15 g", 5, 0, 1, 0),
          item("Miso Sesame Ginger", "36 g", 190, 1, 2, 20),
          item("Pesto Vinaigrette", "39 g", 110, 0, 0, 9),
          item("Red Wine Vinaigrette", "39 g", 180, 0, 2, 19),
          item("Spicy Cashew", "45 g", 170, 3, 4, 15),
          item("Sweetgreen Hot Sauce", "28 g", 10, 1, 2, 0),
          item("Umami Seasoning", "1 serving", 0, 0, 0, 0),
        ],
      },
    ],
  },
};
